/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.freefair.lombok") version "8.14"
}

dependencies {
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.commons.io.commons.io)
    compileOnly(libs.org.jetbrains.annotations)
    compileOnly(libs.com.zaxxer.hikaricp)
    compileOnly(project(":alpslib-utils"))
}

description = "AlpsLib-IO"
version = "1.2.0"
