/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://mvn.alps-bte.com/repository/alps-bte/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.fancyinnovations.com/releases")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }
}

group = "com.alpsbte.alpslib"
java.sourceCompatibility = JavaVersion.VERSION_21

val ORG_GRADLE_PROJECT_alpsMavenUser: String? = project.findProperty("alpsMavenUser") as String?
val ORG_GRADLE_PROJECT_alpsMavenPassword: String? = project.findProperty("alpsMavenPassword") as String?

// configure the project’s PublishingExtension, not the plugin DSL
configure<PublishingExtension> {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            credentials {
                username = ORG_GRADLE_PROJECT_alpsMavenUser
                password = ORG_GRADLE_PROJECT_alpsMavenPassword
            }
            url = uri("https://mvn.alps-bte.com/repository/alps-bte/")
        }
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
