/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.github.decentsoftware.eu.decentholograms.x1)
}

description = "AlpsLib-Hologram"
version = "1.1.1"