/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.de.oliver.fancynpcs)
    compileOnly(libs.com.github.decentsoftware.eu.decentholograms)
    compileOnly(project(":alpslib-hologram"))
}

description = "AlpsLib-NPC"
version = "1.0.37"
