name: Build and Deploy AlpsLib-libpsterra

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'libpsterra/build.gradle.kts'
    #  - 'libpsterra/**'
    #  - '.github/workflows/deploy-libpsterra.yml'
    #  - 'gradle/**'
    #  - 'buildSrc/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :alpslib-libpsterra:build

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        run: ./gradlew :alpslib-libpsterra:publish
        env:
          ORG_GRADLE_PROJECT_alpsMavenUser: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_alpsMavenPassword: ${{ secrets.MAVEN_PASSWORD }}