name: Build and Deploy AlpsLib-Hologram

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'hologram/build.gradle.kts'
    #  - 'hologram/**'
    #  - '.github/workflows/deploy-hologram.yml'
    #  - 'gradle/**'
   #   - 'buildSrc/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew :alpslib-hologram:build

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        run: ./gradlew :alpslib-hologram:publish
        env:
          alpsMavenUser: ${{ secrets.MAVEN_USERNAME }}
          alpsMavenPassword: ${{ secrets.MAVEN_PASSWORD }}